apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
  namespace: kubeapp-dev
data:
#  host: "localhost"
#  port: "3306"
#  dbName: "MarketplaceDB"
  custom-my.cnf: |+
    [mysqld]
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    skip-character-set-client-handshake
    max_connections=1000
    innodb_flush_log_at_trx_commit=2
    innodb_buffer_pool_size=512M
    innodb_log_file_size=256M
    innodb_log_buffer_size=128M
    innodb_file_per_table=1
    lower_case_table_names=1
    log_bin_trust_function_creators=1
