apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: kubeapp-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # adjust the size based on your requirements
