apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: kubeapp-dev
data:
  host: "bG9jYWxob3N0"
  port: "MzMwNg=="
  dbName: "TWFya2V0cGxhY2VEQg=="
  root: "cGFzc3dvcmQ="
  user: "dXNlcg=="
  password: "cGFzc3dvcmQ="



#  host: "localhost"
#  port: "3306"
#  dbName: "MarketplaceDB"
#  root: "password"
#  user: "user"
#  password: "password"


#  spring.datasource.url: "amRiYzpteXNxbDovLzE5Mi4xNjguNDkuMTozMzA2L01hcmtldHBsYWNlREI="


#  jdbc:mysql://db:3306/MarketplaceDB