apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: kubeapp-dev
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30009
  type: NodePort
  selector:
    app: db-deployment


