apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeapp-configmap
  namespace: kubeapp-dev
data:
  application.yaml: |+
    server:
      port: 8080
      servlet:
        context-path: /kubeapp
    spring:
      main:
        allow-bean-definition-overriding: true
      datasource:
        url: jdbc:mysql://192.168.65.254:3306/MarketplaceDB
        username: user
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
    
    
    

#    spring:
#      datasource:
#        username: ${SPRING_DATASOURCE_USERNAME}
#        password: ${SPRING_DATASOURCE_PASSWORD}
#        url: ${SPRING_DATASOURCE_URL}
#        driver-class-name: com.mysql.cj.jdbc.Driver
#    spring:
#      datasource:
#        url: jdbc:mysql://192.168.49.1:3306/MarketplaceDB
#        username: user
#        password: password
#        driver-class-name: com.mysql.cj.jdbc.Driver
    
