apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeapp-deployment
  namespace: kubeapp-dev
  labels:
    app: kubeapp-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeapp-deployment
  template:
    metadata:
      labels:
        app: kubeapp-deployment
    spec:
      hostAliases:
        - ip: 127.0.0.1
          hostnames:
            - localhost
      containers:
      - name: kubeapp-deployment
        image: kubeapp:1.7
        imagePullPolicy: Never
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /kubeapp/actuator/health
            port: http
          failureThreshold: 3
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /kubeapp/actuator/health
            port: http
          failureThreshold: 3
          periodSeconds: 30
        env:
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx1024m"
        - name: CONFIG_FILE
          value: "--spring.config.location=/home/app/config/application.yaml"
        - name: TIME_ZONE
          value: "-Dlogback.timezone=Asia/Bangkok"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: kubeapp-secret
              key: spring.datasource.username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kubeapp-secret
              key: spring.datasource.password
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: kubeapp-secret
              key: spring.datasource.url
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: kubeapp-volume
          mountPath: /home/app/config/application.yaml
          subPath: application.yaml
      volumes:
      - name: kubeapp-volume
        configMap:
          name: kubeapp-configmap

